version: '3'
services:
  nginx_proxy:
    restart: always
    image: staticfloat/nginx-certbot
    ports:
        - 80:80/tcp
        - 443:443/tcp
    environment:
        CERTBOT_EMAIL: jamesthesken@gmail.com
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_HOST=${PGHOST}
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_PORT=${PGPORT}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/:/data
  react-app:
    build:
      context: ./heatmap
      dockerfile: Dockerfile.prod
    volumes:
      - /app/node_modules
      - ./heatmap:/app
#    expose:
#      - "3000"
    ports:
      - '3000:3000'
    restart: on-failure
    container_name: react-app
  express-api:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - '3001:3001'
    restart: on-failure
    container_name: express-api
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
      - ./server:/app # Look at the server directory and copy everything into the app folder in the container
    environment:
      - PGUSER=${PGUSER}
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}
volumes:
  letsencrypt:
